// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: pokerreferee.proto

package pokerrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DraftKind tells a client what it is being asked to sign.
//
// A settlement draft is adaptor-locked: the owner of an input contributes a
// pre-signature that only completes for the branch that won, which is what
// keeps one branch from being broadcast in place of another. An abort draft
// has no branches to choose between - it returns every seat its own stake - so
// there is nothing to gate and every signature on it is an ordinary one,
// including the one over the signer's own input.
type DraftKind int32

const (
	DraftKind_DRAFT_KIND_SETTLEMENT DraftKind = 0
	DraftKind_DRAFT_KIND_ABORT      DraftKind = 1
)

// Enum value maps for DraftKind.
var (
	DraftKind_name = map[int32]string{
		0: "DRAFT_KIND_SETTLEMENT",
		1: "DRAFT_KIND_ABORT",
	}
	DraftKind_value = map[string]int32{
		"DRAFT_KIND_SETTLEMENT": 0,
		"DRAFT_KIND_ABORT":      1,
	}
)

func (x DraftKind) Enum() *DraftKind {
	p := new(DraftKind)
	*p = x
	return p
}

func (x DraftKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DraftKind) Descriptor() protoreflect.EnumDescriptor {
	return file_pokerreferee_proto_enumTypes[0].Descriptor()
}

func (DraftKind) Type() protoreflect.EnumType {
	return &file_pokerreferee_proto_enumTypes[0]
}

func (x DraftKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DraftKind.Descriptor instead.
func (DraftKind) EnumDescriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{0}
}

type OpenEscrowRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AmountAtoms uint64                 `protobuf:"varint,1,opt,name=amount_atoms,json=amountAtoms,proto3" json:"amount_atoms,omitempty"`
	CsvBlocks   uint32                 `protobuf:"varint,2,opt,name=csv_blocks,json=csvBlocks,proto3" json:"csv_blocks,omitempty"`
	Token       string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                             // auth token from Login
	CompPubkey  []byte                 `protobuf:"bytes,4,opt,name=comp_pubkey,json=compPubkey,proto3" json:"comp_pubkey,omitempty"` // 33-byte compressed session key X = xG
	// Roster the escrow is bound to. The settlement branch of the redeem script
	// carries one key per table member, so the script - and therefore the
	// deposit address - cannot be derived until every seat has published a key.
	TableId       string `protobuf:"bytes,5,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	SessionId     string `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenEscrowRequest) Reset() {
	*x = OpenEscrowRequest{}
	mi := &file_pokerreferee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenEscrowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenEscrowRequest) ProtoMessage() {}

func (x *OpenEscrowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenEscrowRequest.ProtoReflect.Descriptor instead.
func (*OpenEscrowRequest) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{0}
}

func (x *OpenEscrowRequest) GetAmountAtoms() uint64 {
	if x != nil {
		return x.AmountAtoms
	}
	return 0
}

func (x *OpenEscrowRequest) GetCsvBlocks() uint32 {
	if x != nil {
		return x.CsvBlocks
	}
	return 0
}

func (x *OpenEscrowRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *OpenEscrowRequest) GetCompPubkey() []byte {
	if x != nil {
		return x.CompPubkey
	}
	return nil
}

func (x *OpenEscrowRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *OpenEscrowRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type OpenEscrowResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	EscrowId              string                 `protobuf:"bytes,1,opt,name=escrow_id,json=escrowId,proto3" json:"escrow_id,omitempty"`
	DepositAddr           string                 `protobuf:"bytes,2,opt,name=deposit_addr,json=depositAddr,proto3" json:"deposit_addr,omitempty"`               // human-readable deposit address
	RedeemScriptHex       string                 `protobuf:"bytes,3,opt,name=redeem_script_hex,json=redeemScriptHex,proto3" json:"redeem_script_hex,omitempty"` // hex-encoded redeem script for the escrow
	PkScriptHex           string                 `protobuf:"bytes,4,opt,name=pk_script_hex,json=pkScriptHex,proto3" json:"pk_script_hex,omitempty"`             // hex-encoded pkScript to watch for funding
	MatchId               string                 `protobuf:"bytes,5,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`                           // table_id|session_id
	RequiredConfirmations uint32                 `protobuf:"varint,6,opt,name=required_confirmations,json=requiredConfirmations,proto3" json:"required_confirmations,omitempty"`
	// roster_ready reports whether every seat has published a session key. While
	// false the escrow exists but has no deposit address yet: deposit_addr,
	// redeem_script_hex and pk_script_hex are empty and funding must wait.
	RosterReady bool `protobuf:"varint,7,opt,name=roster_ready,json=rosterReady,proto3" json:"roster_ready,omitempty"`
	// member_pubkeys is the canonical roster the redeem script commits to, in
	// the order the script checks. Clients rebuild the script from this to check
	// the deposit address rather than trusting the one they were handed.
	MemberPubkeys [][]byte `protobuf:"bytes,8,rep,name=member_pubkeys,json=memberPubkeys,proto3" json:"member_pubkeys,omitempty"`
	// seats_pending counts seats that have not published a key yet.
	SeatsPending  uint32 `protobuf:"varint,9,opt,name=seats_pending,json=seatsPending,proto3" json:"seats_pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenEscrowResponse) Reset() {
	*x = OpenEscrowResponse{}
	mi := &file_pokerreferee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenEscrowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenEscrowResponse) ProtoMessage() {}

func (x *OpenEscrowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenEscrowResponse.ProtoReflect.Descriptor instead.
func (*OpenEscrowResponse) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{1}
}

func (x *OpenEscrowResponse) GetEscrowId() string {
	if x != nil {
		return x.EscrowId
	}
	return ""
}

func (x *OpenEscrowResponse) GetDepositAddr() string {
	if x != nil {
		return x.DepositAddr
	}
	return ""
}

func (x *OpenEscrowResponse) GetRedeemScriptHex() string {
	if x != nil {
		return x.RedeemScriptHex
	}
	return ""
}

func (x *OpenEscrowResponse) GetPkScriptHex() string {
	if x != nil {
		return x.PkScriptHex
	}
	return ""
}

func (x *OpenEscrowResponse) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *OpenEscrowResponse) GetRequiredConfirmations() uint32 {
	if x != nil {
		return x.RequiredConfirmations
	}
	return 0
}

func (x *OpenEscrowResponse) GetRosterReady() bool {
	if x != nil {
		return x.RosterReady
	}
	return false
}

func (x *OpenEscrowResponse) GetMemberPubkeys() [][]byte {
	if x != nil {
		return x.MemberPubkeys
	}
	return nil
}

func (x *OpenEscrowResponse) GetSeatsPending() uint32 {
	if x != nil {
		return x.SeatsPending
	}
	return 0
}

type BindEscrowRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Outpoint        string                 `protobuf:"bytes,1,opt,name=outpoint,proto3" json:"outpoint,omitempty"` // funding outpoint txid:vout
	TableId         string                 `protobuf:"bytes,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SeatIndex       uint32                 `protobuf:"varint,4,opt,name=seat_index,json=seatIndex,proto3" json:"seat_index,omitempty"`
	MatchId         string                 `protobuf:"bytes,5,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"` // optional pre-derived match_id; table+session preferred
	Token           string                 `protobuf:"bytes,6,opt,name=token,proto3" json:"token,omitempty"`                    // auth token from Login (may also come from metadata)
	RedeemScriptHex string                 `protobuf:"bytes,7,opt,name=redeem_script_hex,json=redeemScriptHex,proto3" json:"redeem_script_hex,omitempty"`
	CsvBlocks       uint32                 `protobuf:"varint,8,opt,name=csv_blocks,json=csvBlocks,proto3" json:"csv_blocks,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BindEscrowRequest) Reset() {
	*x = BindEscrowRequest{}
	mi := &file_pokerreferee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindEscrowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindEscrowRequest) ProtoMessage() {}

func (x *BindEscrowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindEscrowRequest.ProtoReflect.Descriptor instead.
func (*BindEscrowRequest) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{2}
}

func (x *BindEscrowRequest) GetOutpoint() string {
	if x != nil {
		return x.Outpoint
	}
	return ""
}

func (x *BindEscrowRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *BindEscrowRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BindEscrowRequest) GetSeatIndex() uint32 {
	if x != nil {
		return x.SeatIndex
	}
	return 0
}

func (x *BindEscrowRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *BindEscrowRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *BindEscrowRequest) GetRedeemScriptHex() string {
	if x != nil {
		return x.RedeemScriptHex
	}
	return ""
}

func (x *BindEscrowRequest) GetCsvBlocks() uint32 {
	if x != nil {
		return x.CsvBlocks
	}
	return 0
}

type BindEscrowResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MatchId             string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	TableId             string                 `protobuf:"bytes,2,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	SessionId           string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SeatIndex           uint32                 `protobuf:"varint,4,opt,name=seat_index,json=seatIndex,proto3" json:"seat_index,omitempty"`
	EscrowId            string                 `protobuf:"bytes,5,opt,name=escrow_id,json=escrowId,proto3" json:"escrow_id,omitempty"`
	EscrowReady         bool                   `protobuf:"varint,6,opt,name=escrow_ready,json=escrowReady,proto3" json:"escrow_ready,omitempty"`
	AmountAtoms         uint64                 `protobuf:"varint,7,opt,name=amount_atoms,json=amountAtoms,proto3" json:"amount_atoms,omitempty"`
	RequiredAmountAtoms uint64                 `protobuf:"varint,8,opt,name=required_amount_atoms,json=requiredAmountAtoms,proto3" json:"required_amount_atoms,omitempty"`
	Outpoint            string                 `protobuf:"bytes,9,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BindEscrowResponse) Reset() {
	*x = BindEscrowResponse{}
	mi := &file_pokerreferee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindEscrowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindEscrowResponse) ProtoMessage() {}

func (x *BindEscrowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindEscrowResponse.ProtoReflect.Descriptor instead.
func (*BindEscrowResponse) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{3}
}

func (x *BindEscrowResponse) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *BindEscrowResponse) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *BindEscrowResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BindEscrowResponse) GetSeatIndex() uint32 {
	if x != nil {
		return x.SeatIndex
	}
	return 0
}

func (x *BindEscrowResponse) GetEscrowId() string {
	if x != nil {
		return x.EscrowId
	}
	return ""
}

func (x *BindEscrowResponse) GetEscrowReady() bool {
	if x != nil {
		return x.EscrowReady
	}
	return false
}

func (x *BindEscrowResponse) GetAmountAtoms() uint64 {
	if x != nil {
		return x.AmountAtoms
	}
	return 0
}

func (x *BindEscrowResponse) GetRequiredAmountAtoms() uint64 {
	if x != nil {
		return x.RequiredAmountAtoms
	}
	return 0
}

func (x *BindEscrowResponse) GetOutpoint() string {
	if x != nil {
		return x.Outpoint
	}
	return ""
}

type GetEscrowStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EscrowId      string                 `protobuf:"bytes,1,opt,name=escrow_id,json=escrowId,proto3" json:"escrow_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // auth token from Login (may also come from metadata)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEscrowStatusRequest) Reset() {
	*x = GetEscrowStatusRequest{}
	mi := &file_pokerreferee_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEscrowStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEscrowStatusRequest) ProtoMessage() {}

func (x *GetEscrowStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEscrowStatusRequest.ProtoReflect.Descriptor instead.
func (*GetEscrowStatusRequest) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{4}
}

func (x *GetEscrowStatusRequest) GetEscrowId() string {
	if x != nil {
		return x.EscrowId
	}
	return ""
}

func (x *GetEscrowStatusRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetEscrowStatusResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	EscrowId              string                 `protobuf:"bytes,1,opt,name=escrow_id,json=escrowId,proto3" json:"escrow_id,omitempty"`
	Confs                 uint32                 `protobuf:"varint,2,opt,name=confs,proto3" json:"confs,omitempty"`
	UtxoCount             uint32                 `protobuf:"varint,3,opt,name=utxo_count,json=utxoCount,proto3" json:"utxo_count,omitempty"`
	Ok                    bool                   `protobuf:"varint,4,opt,name=ok,proto3" json:"ok,omitempty"`
	UpdatedAtUnix         int64                  `protobuf:"varint,5,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	FundingTxid           string                 `protobuf:"bytes,6,opt,name=funding_txid,json=fundingTxid,proto3" json:"funding_txid,omitempty"`
	FundingVout           uint32                 `protobuf:"varint,7,opt,name=funding_vout,json=fundingVout,proto3" json:"funding_vout,omitempty"`
	AmountAtoms           uint64                 `protobuf:"varint,8,opt,name=amount_atoms,json=amountAtoms,proto3" json:"amount_atoms,omitempty"`
	CsvBlocks             uint32                 `protobuf:"varint,10,opt,name=csv_blocks,json=csvBlocks,proto3" json:"csv_blocks,omitempty"`
	RequiredConfirmations uint32                 `protobuf:"varint,11,opt,name=required_confirmations,json=requiredConfirmations,proto3" json:"required_confirmations,omitempty"`
	MatureForCsv          bool                   `protobuf:"varint,12,opt,name=mature_for_csv,json=matureForCsv,proto3" json:"mature_for_csv,omitempty"`
	FundingState          string                 `protobuf:"bytes,13,opt,name=funding_state,json=fundingState,proto3" json:"funding_state,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetEscrowStatusResponse) Reset() {
	*x = GetEscrowStatusResponse{}
	mi := &file_pokerreferee_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEscrowStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEscrowStatusResponse) ProtoMessage() {}

func (x *GetEscrowStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEscrowStatusResponse.ProtoReflect.Descriptor instead.
func (*GetEscrowStatusResponse) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{5}
}

func (x *GetEscrowStatusResponse) GetEscrowId() string {
	if x != nil {
		return x.EscrowId
	}
	return ""
}

func (x *GetEscrowStatusResponse) GetConfs() uint32 {
	if x != nil {
		return x.Confs
	}
	return 0
}

func (x *GetEscrowStatusResponse) GetUtxoCount() uint32 {
	if x != nil {
		return x.UtxoCount
	}
	return 0
}

func (x *GetEscrowStatusResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetEscrowStatusResponse) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

func (x *GetEscrowStatusResponse) GetFundingTxid() string {
	if x != nil {
		return x.FundingTxid
	}
	return ""
}

func (x *GetEscrowStatusResponse) GetFundingVout() uint32 {
	if x != nil {
		return x.FundingVout
	}
	return 0
}

func (x *GetEscrowStatusResponse) GetAmountAtoms() uint64 {
	if x != nil {
		return x.AmountAtoms
	}
	return 0
}

func (x *GetEscrowStatusResponse) GetCsvBlocks() uint32 {
	if x != nil {
		return x.CsvBlocks
	}
	return 0
}

func (x *GetEscrowStatusResponse) GetRequiredConfirmations() uint32 {
	if x != nil {
		return x.RequiredConfirmations
	}
	return 0
}

func (x *GetEscrowStatusResponse) GetMatureForCsv() bool {
	if x != nil {
		return x.MatureForCsv
	}
	return false
}

func (x *GetEscrowStatusResponse) GetFundingState() string {
	if x != nil {
		return x.FundingState
	}
	return ""
}

type PublishSessionKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EscrowId      string                 `protobuf:"bytes,1,opt,name=escrow_id,json=escrowId,proto3" json:"escrow_id,omitempty"`
	CompPubkey    []byte                 `protobuf:"bytes,2,opt,name=comp_pubkey,json=compPubkey,proto3" json:"comp_pubkey,omitempty"` // 33-byte compressed session key X = xG
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishSessionKeyRequest) Reset() {
	*x = PublishSessionKeyRequest{}
	mi := &file_pokerreferee_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishSessionKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishSessionKeyRequest) ProtoMessage() {}

func (x *PublishSessionKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishSessionKeyRequest.ProtoReflect.Descriptor instead.
func (*PublishSessionKeyRequest) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{6}
}

func (x *PublishSessionKeyRequest) GetEscrowId() string {
	if x != nil {
		return x.EscrowId
	}
	return ""
}

func (x *PublishSessionKeyRequest) GetCompPubkey() []byte {
	if x != nil {
		return x.CompPubkey
	}
	return nil
}

type PublishSessionKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishSessionKeyResponse) Reset() {
	*x = PublishSessionKeyResponse{}
	mi := &file_pokerreferee_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishSessionKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishSessionKeyResponse) ProtoMessage() {}

func (x *PublishSessionKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishSessionKeyResponse.ProtoReflect.Descriptor instead.
func (*PublishSessionKeyResponse) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{7}
}

func (x *PublishSessionKeyResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PublishSessionKeyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SettlementStreamMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*SettlementStreamMessage_Hello
	//	*SettlementStreamMessage_NeedPreSigs
	//	*SettlementStreamMessage_ProvidePreSigs
	//	*SettlementStreamMessage_VerifyOk
	//	*SettlementStreamMessage_Error
	Msg           isSettlementStreamMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlementStreamMessage) Reset() {
	*x = SettlementStreamMessage{}
	mi := &file_pokerreferee_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementStreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementStreamMessage) ProtoMessage() {}

func (x *SettlementStreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementStreamMessage.ProtoReflect.Descriptor instead.
func (*SettlementStreamMessage) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{8}
}

func (x *SettlementStreamMessage) GetMsg() isSettlementStreamMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *SettlementStreamMessage) GetHello() *SettlementHello {
	if x != nil {
		if x, ok := x.Msg.(*SettlementStreamMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *SettlementStreamMessage) GetNeedPreSigs() *NeedPreSigs {
	if x != nil {
		if x, ok := x.Msg.(*SettlementStreamMessage_NeedPreSigs); ok {
			return x.NeedPreSigs
		}
	}
	return nil
}

func (x *SettlementStreamMessage) GetProvidePreSigs() *ProvidePreSigs {
	if x != nil {
		if x, ok := x.Msg.(*SettlementStreamMessage_ProvidePreSigs); ok {
			return x.ProvidePreSigs
		}
	}
	return nil
}

func (x *SettlementStreamMessage) GetVerifyOk() *VerifyPreSigsOk {
	if x != nil {
		if x, ok := x.Msg.(*SettlementStreamMessage_VerifyOk); ok {
			return x.VerifyOk
		}
	}
	return nil
}

func (x *SettlementStreamMessage) GetError() *SettlementError {
	if x != nil {
		if x, ok := x.Msg.(*SettlementStreamMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isSettlementStreamMessage_Msg interface {
	isSettlementStreamMessage_Msg()
}

type SettlementStreamMessage_Hello struct {
	Hello *SettlementHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type SettlementStreamMessage_NeedPreSigs struct {
	NeedPreSigs *NeedPreSigs `protobuf:"bytes,2,opt,name=need_pre_sigs,json=needPreSigs,proto3,oneof"`
}

type SettlementStreamMessage_ProvidePreSigs struct {
	ProvidePreSigs *ProvidePreSigs `protobuf:"bytes,3,opt,name=provide_pre_sigs,json=providePreSigs,proto3,oneof"`
}

type SettlementStreamMessage_VerifyOk struct {
	VerifyOk *VerifyPreSigsOk `protobuf:"bytes,4,opt,name=verify_ok,json=verifyOk,proto3,oneof"`
}

type SettlementStreamMessage_Error struct {
	Error *SettlementError `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*SettlementStreamMessage_Hello) isSettlementStreamMessage_Msg() {}

func (*SettlementStreamMessage_NeedPreSigs) isSettlementStreamMessage_Msg() {}

func (*SettlementStreamMessage_ProvidePreSigs) isSettlementStreamMessage_Msg() {}

func (*SettlementStreamMessage_VerifyOk) isSettlementStreamMessage_Msg() {}

func (*SettlementStreamMessage_Error) isSettlementStreamMessage_Msg() {}

// Client → Server
type SettlementHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`          // table_id|session_id
	EscrowId      string                 `protobuf:"bytes,2,opt,name=escrow_id,json=escrowId,proto3" json:"escrow_id,omitempty"`       // escrow session owned by caller
	CompPubkey    []byte                 `protobuf:"bytes,3,opt,name=comp_pubkey,json=compPubkey,proto3" json:"comp_pubkey,omitempty"` // session pubkey for verification
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`                             // auth token from Login
	TableId       string                 `protobuf:"bytes,5,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	SeatIndex     uint32                 `protobuf:"varint,6,opt,name=seat_index,json=seatIndex,proto3" json:"seat_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlementHello) Reset() {
	*x = SettlementHello{}
	mi := &file_pokerreferee_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementHello) ProtoMessage() {}

func (x *SettlementHello) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementHello.ProtoReflect.Descriptor instead.
func (*SettlementHello) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{9}
}

func (x *SettlementHello) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *SettlementHello) GetEscrowId() string {
	if x != nil {
		return x.EscrowId
	}
	return ""
}

func (x *SettlementHello) GetCompPubkey() []byte {
	if x != nil {
		return x.CompPubkey
	}
	return nil
}

func (x *SettlementHello) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SettlementHello) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *SettlementHello) GetSeatIndex() uint32 {
	if x != nil {
		return x.SeatIndex
	}
	return 0
}

// Server → Client: request presigs for a specific branch/winner seat.
type NeedPreSigs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Branch        int32                  `protobuf:"varint,2,opt,name=branch,proto3" json:"branch,omitempty"` // winner seat index; unused for abort drafts
	DraftTxHex    string                 `protobuf:"bytes,3,opt,name=draft_tx_hex,json=draftTxHex,proto3" json:"draft_tx_hex,omitempty"`
	Inputs        []*NeedPreSigsInput    `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Kind          DraftKind              `protobuf:"varint,5,opt,name=kind,proto3,enum=poker.DraftKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeedPreSigs) Reset() {
	*x = NeedPreSigs{}
	mi := &file_pokerreferee_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeedPreSigs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeedPreSigs) ProtoMessage() {}

func (x *NeedPreSigs) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeedPreSigs.ProtoReflect.Descriptor instead.
func (*NeedPreSigs) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{10}
}

func (x *NeedPreSigs) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *NeedPreSigs) GetBranch() int32 {
	if x != nil {
		return x.Branch
	}
	return 0
}

func (x *NeedPreSigs) GetDraftTxHex() string {
	if x != nil {
		return x.DraftTxHex
	}
	return ""
}

func (x *NeedPreSigs) GetInputs() []*NeedPreSigsInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *NeedPreSigs) GetKind() DraftKind {
	if x != nil {
		return x.Kind
	}
	return DraftKind_DRAFT_KIND_SETTLEMENT
}

type NeedPreSigsInput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InputId         string                 `protobuf:"bytes,1,opt,name=input_id,json=inputId,proto3" json:"input_id,omitempty"`                           // stable input identifier (e.g., txid:vout)
	RedeemScriptHex string                 `protobuf:"bytes,2,opt,name=redeem_script_hex,json=redeemScriptHex,proto3" json:"redeem_script_hex,omitempty"` // redeem script for this input
	SighashHex      string                 `protobuf:"bytes,3,opt,name=sighash_hex,json=sighashHex,proto3" json:"sighash_hex,omitempty"`                  // 32-byte SigHashAll digest (m)
	AdaptorPointHex string                 `protobuf:"bytes,4,opt,name=adaptor_point_hex,json=adaptorPointHex,proto3" json:"adaptor_point_hex,omitempty"` // compressed adaptor point T for this branch
	InputIndex      uint32                 `protobuf:"varint,5,opt,name=input_index,json=inputIndex,proto3" json:"input_index,omitempty"`                 // index inside the draft transaction
	AmountAtoms     uint64                 `protobuf:"varint,6,opt,name=amount_atoms,json=amountAtoms,proto3" json:"amount_atoms,omitempty"`              // input amount to bind sighash
	// owner_pubkey is the session key of the player whose escrow this input is.
	// Every input of every branch is sent to every player now: the escrow's
	// settlement branch needs a signature from the whole table, so a client
	// adaptor-presigns the input it owns and plainly co-signs all the others.
	OwnerPubkey   []byte `protobuf:"bytes,7,opt,name=owner_pubkey,json=ownerPubkey,proto3" json:"owner_pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeedPreSigsInput) Reset() {
	*x = NeedPreSigsInput{}
	mi := &file_pokerreferee_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeedPreSigsInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeedPreSigsInput) ProtoMessage() {}

func (x *NeedPreSigsInput) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeedPreSigsInput.ProtoReflect.Descriptor instead.
func (*NeedPreSigsInput) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{11}
}

func (x *NeedPreSigsInput) GetInputId() string {
	if x != nil {
		return x.InputId
	}
	return ""
}

func (x *NeedPreSigsInput) GetRedeemScriptHex() string {
	if x != nil {
		return x.RedeemScriptHex
	}
	return ""
}

func (x *NeedPreSigsInput) GetSighashHex() string {
	if x != nil {
		return x.SighashHex
	}
	return ""
}

func (x *NeedPreSigsInput) GetAdaptorPointHex() string {
	if x != nil {
		return x.AdaptorPointHex
	}
	return ""
}

func (x *NeedPreSigsInput) GetInputIndex() uint32 {
	if x != nil {
		return x.InputIndex
	}
	return 0
}

func (x *NeedPreSigsInput) GetAmountAtoms() uint64 {
	if x != nil {
		return x.AmountAtoms
	}
	return 0
}

func (x *NeedPreSigsInput) GetOwnerPubkey() []byte {
	if x != nil {
		return x.OwnerPubkey
	}
	return nil
}

// Client → Server: signatures for the requested branch. presigs covers the
// caller's own inputs (adaptor-locked, so only the winning branch completes);
// cosigs covers every other input on the same draft.
type ProvidePreSigs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Branch        int32                  `protobuf:"varint,2,opt,name=branch,proto3" json:"branch,omitempty"` // winner seat index; unused for abort drafts
	Presigs       []*PreSignature        `protobuf:"bytes,3,rep,name=presigs,proto3" json:"presigs,omitempty"`
	Cosigs        []*CoSignature         `protobuf:"bytes,4,rep,name=cosigs,proto3" json:"cosigs,omitempty"`
	Kind          DraftKind              `protobuf:"varint,5,opt,name=kind,proto3,enum=poker.DraftKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvidePreSigs) Reset() {
	*x = ProvidePreSigs{}
	mi := &file_pokerreferee_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvidePreSigs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvidePreSigs) ProtoMessage() {}

func (x *ProvidePreSigs) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvidePreSigs.ProtoReflect.Descriptor instead.
func (*ProvidePreSigs) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{12}
}

func (x *ProvidePreSigs) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *ProvidePreSigs) GetBranch() int32 {
	if x != nil {
		return x.Branch
	}
	return 0
}

func (x *ProvidePreSigs) GetPresigs() []*PreSignature {
	if x != nil {
		return x.Presigs
	}
	return nil
}

func (x *ProvidePreSigs) GetCosigs() []*CoSignature {
	if x != nil {
		return x.Cosigs
	}
	return nil
}

func (x *ProvidePreSigs) GetKind() DraftKind {
	if x != nil {
		return x.Kind
	}
	return DraftKind_DRAFT_KIND_SETTLEMENT
}

type PreSignature struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InputId          string                 `protobuf:"bytes,1,opt,name=input_id,json=inputId,proto3" json:"input_id,omitempty"`
	RPrimeCompactHex string                 `protobuf:"bytes,2,opt,name=r_prime_compact_hex,json=rPrimeCompactHex,proto3" json:"r_prime_compact_hex,omitempty"` // 33-byte even-Y R'
	SPrimeHex        string                 `protobuf:"bytes,3,opt,name=s_prime_hex,json=sPrimeHex,proto3" json:"s_prime_hex,omitempty"`                        // 32-byte s'
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PreSignature) Reset() {
	*x = PreSignature{}
	mi := &file_pokerreferee_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreSignature) ProtoMessage() {}

func (x *PreSignature) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreSignature.ProtoReflect.Descriptor instead.
func (*PreSignature) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{13}
}

func (x *PreSignature) GetInputId() string {
	if x != nil {
		return x.InputId
	}
	return ""
}

func (x *PreSignature) GetRPrimeCompactHex() string {
	if x != nil {
		return x.RPrimeCompactHex
	}
	return ""
}

func (x *PreSignature) GetSPrimeHex() string {
	if x != nil {
		return x.SPrimeHex
	}
	return ""
}

// CoSignature is an ordinary consensus Schnorr signature over a draft input the
// signer does not own. It is not adaptor-locked: branch selection is already
// gated by the owner's presig, and these only prove the table agreed.
type CoSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputId       string                 `protobuf:"bytes,1,opt,name=input_id,json=inputId,proto3" json:"input_id,omitempty"`
	SignerPubkey  []byte                 `protobuf:"bytes,2,opt,name=signer_pubkey,json=signerPubkey,proto3" json:"signer_pubkey,omitempty"` // whose signature this is
	SigHex        string                 `protobuf:"bytes,3,opt,name=sig_hex,json=sigHex,proto3" json:"sig_hex,omitempty"`                   // 65 bytes: 64 [r,s] plus the hash type byte
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoSignature) Reset() {
	*x = CoSignature{}
	mi := &file_pokerreferee_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoSignature) ProtoMessage() {}

func (x *CoSignature) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoSignature.ProtoReflect.Descriptor instead.
func (*CoSignature) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{14}
}

func (x *CoSignature) GetInputId() string {
	if x != nil {
		return x.InputId
	}
	return ""
}

func (x *CoSignature) GetSignerPubkey() []byte {
	if x != nil {
		return x.SignerPubkey
	}
	return nil
}

func (x *CoSignature) GetSigHex() string {
	if x != nil {
		return x.SigHex
	}
	return ""
}

// Server → Client: indicates presigs were verified and stored.
type VerifyPreSigsOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Branch        int32                  `protobuf:"varint,2,opt,name=branch,proto3" json:"branch,omitempty"` // unused for abort drafts
	Kind          DraftKind              `protobuf:"varint,3,opt,name=kind,proto3,enum=poker.DraftKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPreSigsOk) Reset() {
	*x = VerifyPreSigsOk{}
	mi := &file_pokerreferee_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPreSigsOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPreSigsOk) ProtoMessage() {}

func (x *VerifyPreSigsOk) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPreSigsOk.ProtoReflect.Descriptor instead.
func (*VerifyPreSigsOk) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{15}
}

func (x *VerifyPreSigsOk) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *VerifyPreSigsOk) GetBranch() int32 {
	if x != nil {
		return x.Branch
	}
	return 0
}

func (x *VerifyPreSigsOk) GetKind() DraftKind {
	if x != nil {
		return x.Kind
	}
	return DraftKind_DRAFT_KIND_SETTLEMENT
}

// Server → Client: terminal error for this stream.
type SettlementError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlementError) Reset() {
	*x = SettlementError{}
	mi := &file_pokerreferee_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementError) ProtoMessage() {}

func (x *SettlementError) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementError.ProtoReflect.Descriptor instead.
func (*SettlementError) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{16}
}

func (x *SettlementError) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *SettlementError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetFinalizeBundleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	WinnerSeat    int32                  `protobuf:"varint,2,opt,name=winner_seat,json=winnerSeat,proto3" json:"winner_seat,omitempty"` // branch to finalize
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFinalizeBundleRequest) Reset() {
	*x = GetFinalizeBundleRequest{}
	mi := &file_pokerreferee_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFinalizeBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFinalizeBundleRequest) ProtoMessage() {}

func (x *GetFinalizeBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFinalizeBundleRequest.ProtoReflect.Descriptor instead.
func (*GetFinalizeBundleRequest) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{17}
}

func (x *GetFinalizeBundleRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *GetFinalizeBundleRequest) GetWinnerSeat() int32 {
	if x != nil {
		return x.WinnerSeat
	}
	return 0
}

type GetFinalizeBundleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Branch        int32                  `protobuf:"varint,2,opt,name=branch,proto3" json:"branch,omitempty"`
	DraftTxHex    string                 `protobuf:"bytes,3,opt,name=draft_tx_hex,json=draftTxHex,proto3" json:"draft_tx_hex,omitempty"` // winning branch draft
	GammaHex      string                 `protobuf:"bytes,4,opt,name=gamma_hex,json=gammaHex,proto3" json:"gamma_hex,omitempty"`         // adaptor secret scalar for this branch
	Inputs        []*FinalizeInput       `protobuf:"bytes,5,rep,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFinalizeBundleResponse) Reset() {
	*x = GetFinalizeBundleResponse{}
	mi := &file_pokerreferee_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFinalizeBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFinalizeBundleResponse) ProtoMessage() {}

func (x *GetFinalizeBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFinalizeBundleResponse.ProtoReflect.Descriptor instead.
func (*GetFinalizeBundleResponse) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{18}
}

func (x *GetFinalizeBundleResponse) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *GetFinalizeBundleResponse) GetBranch() int32 {
	if x != nil {
		return x.Branch
	}
	return 0
}

func (x *GetFinalizeBundleResponse) GetDraftTxHex() string {
	if x != nil {
		return x.DraftTxHex
	}
	return ""
}

func (x *GetFinalizeBundleResponse) GetGammaHex() string {
	if x != nil {
		return x.GammaHex
	}
	return ""
}

func (x *GetFinalizeBundleResponse) GetInputs() []*FinalizeInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type FinalizeInput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InputId          string                 `protobuf:"bytes,1,opt,name=input_id,json=inputId,proto3" json:"input_id,omitempty"`
	RPrimeCompactHex string                 `protobuf:"bytes,2,opt,name=r_prime_compact_hex,json=rPrimeCompactHex,proto3" json:"r_prime_compact_hex,omitempty"`
	SPrimeHex        string                 `protobuf:"bytes,3,opt,name=s_prime_hex,json=sPrimeHex,proto3" json:"s_prime_hex,omitempty"`
	InputIndex       uint32                 `protobuf:"varint,4,opt,name=input_index,json=inputIndex,proto3" json:"input_index,omitempty"`
	RedeemScriptHex  string                 `protobuf:"bytes,5,opt,name=redeem_script_hex,json=redeemScriptHex,proto3" json:"redeem_script_hex,omitempty"`
	// cosigs are the other table members' signatures over this input, which the
	// settlement branch also requires. Ordered as the redeem script checks them;
	// the owner's slot is the one completed from the presig above.
	Cosigs        []*CoSignature `protobuf:"bytes,6,rep,name=cosigs,proto3" json:"cosigs,omitempty"`
	OwnerPubkey   []byte         `protobuf:"bytes,7,opt,name=owner_pubkey,json=ownerPubkey,proto3" json:"owner_pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeInput) Reset() {
	*x = FinalizeInput{}
	mi := &file_pokerreferee_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeInput) ProtoMessage() {}

func (x *FinalizeInput) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeInput.ProtoReflect.Descriptor instead.
func (*FinalizeInput) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{19}
}

func (x *FinalizeInput) GetInputId() string {
	if x != nil {
		return x.InputId
	}
	return ""
}

func (x *FinalizeInput) GetRPrimeCompactHex() string {
	if x != nil {
		return x.RPrimeCompactHex
	}
	return ""
}

func (x *FinalizeInput) GetSPrimeHex() string {
	if x != nil {
		return x.SPrimeHex
	}
	return ""
}

func (x *FinalizeInput) GetInputIndex() uint32 {
	if x != nil {
		return x.InputIndex
	}
	return 0
}

func (x *FinalizeInput) GetRedeemScriptHex() string {
	if x != nil {
		return x.RedeemScriptHex
	}
	return ""
}

func (x *FinalizeInput) GetCosigs() []*CoSignature {
	if x != nil {
		return x.Cosigs
	}
	return nil
}

func (x *FinalizeInput) GetOwnerPubkey() []byte {
	if x != nil {
		return x.OwnerPubkey
	}
	return nil
}

type PostBondRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                        // auth token from Login (may also come from metadata)
	Outpoint      string                 `protobuf:"bytes,2,opt,name=outpoint,proto3" json:"outpoint,omitempty"`                                  // funding outpoint txid:vout of the bond deposit
	BondScriptHex string                 `protobuf:"bytes,3,opt,name=bond_script_hex,json=bondScriptHex,proto3" json:"bond_script_hex,omitempty"` // the timelocked script the deposit pays
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostBondRequest) Reset() {
	*x = PostBondRequest{}
	mi := &file_pokerreferee_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBondRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBondRequest) ProtoMessage() {}

func (x *PostBondRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBondRequest.ProtoReflect.Descriptor instead.
func (*PostBondRequest) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{20}
}

func (x *PostBondRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PostBondRequest) GetOutpoint() string {
	if x != nil {
		return x.Outpoint
	}
	return ""
}

func (x *PostBondRequest) GetBondScriptHex() string {
	if x != nil {
		return x.BondScriptHex
	}
	return ""
}

type GetBondRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBondRequest) Reset() {
	*x = GetBondRequest{}
	mi := &file_pokerreferee_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBondRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBondRequest) ProtoMessage() {}

func (x *GetBondRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBondRequest.ProtoReflect.Descriptor instead.
func (*GetBondRequest) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{21}
}

func (x *GetBondRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type PostBondResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Ok          bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Outpoint    string                 `protobuf:"bytes,2,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	AmountAtoms uint64                 `protobuf:"varint,3,opt,name=amount_atoms,json=amountAtoms,proto3" json:"amount_atoms,omitempty"`
	LockBlocks  uint32                 `protobuf:"varint,4,opt,name=lock_blocks,json=lockBlocks,proto3" json:"lock_blocks,omitempty"`
	Confs       uint32                 `protobuf:"varint,5,opt,name=confs,proto3" json:"confs,omitempty"`
	OwnerPubkey []byte                 `protobuf:"bytes,6,opt,name=owner_pubkey,json=ownerPubkey,proto3" json:"owner_pubkey,omitempty"`
	// required_atoms and required_lock_blocks are the terms this referee
	// demands, so a client can see why a bond was refused - or what to post.
	RequiredAtoms      uint64 `protobuf:"varint,7,opt,name=required_atoms,json=requiredAtoms,proto3" json:"required_atoms,omitempty"`
	RequiredLockBlocks uint32 `protobuf:"varint,8,opt,name=required_lock_blocks,json=requiredLockBlocks,proto3" json:"required_lock_blocks,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PostBondResponse) Reset() {
	*x = PostBondResponse{}
	mi := &file_pokerreferee_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBondResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBondResponse) ProtoMessage() {}

func (x *PostBondResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBondResponse.ProtoReflect.Descriptor instead.
func (*PostBondResponse) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{22}
}

func (x *PostBondResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PostBondResponse) GetOutpoint() string {
	if x != nil {
		return x.Outpoint
	}
	return ""
}

func (x *PostBondResponse) GetAmountAtoms() uint64 {
	if x != nil {
		return x.AmountAtoms
	}
	return 0
}

func (x *PostBondResponse) GetLockBlocks() uint32 {
	if x != nil {
		return x.LockBlocks
	}
	return 0
}

func (x *PostBondResponse) GetConfs() uint32 {
	if x != nil {
		return x.Confs
	}
	return 0
}

func (x *PostBondResponse) GetOwnerPubkey() []byte {
	if x != nil {
		return x.OwnerPubkey
	}
	return nil
}

func (x *PostBondResponse) GetRequiredAtoms() uint64 {
	if x != nil {
		return x.RequiredAtoms
	}
	return 0
}

func (x *PostBondResponse) GetRequiredLockBlocks() uint32 {
	if x != nil {
		return x.RequiredLockBlocks
	}
	return 0
}

type AbortMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // auth token from Login (may also come from metadata)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortMatchRequest) Reset() {
	*x = AbortMatchRequest{}
	mi := &file_pokerreferee_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortMatchRequest) ProtoMessage() {}

func (x *AbortMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortMatchRequest.ProtoReflect.Descriptor instead.
func (*AbortMatchRequest) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{23}
}

func (x *AbortMatchRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *AbortMatchRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AbortMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Txid          string                 `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	Broadcast     bool                   `protobuf:"varint,2,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortMatchResponse) Reset() {
	*x = AbortMatchResponse{}
	mi := &file_pokerreferee_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortMatchResponse) ProtoMessage() {}

func (x *AbortMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortMatchResponse.ProtoReflect.Descriptor instead.
func (*AbortMatchResponse) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{24}
}

func (x *AbortMatchResponse) GetTxid() string {
	if x != nil {
		return x.Txid
	}
	return ""
}

func (x *AbortMatchResponse) GetBroadcast() bool {
	if x != nil {
		return x.Broadcast
	}
	return false
}

type SetPayoutAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`         // active session token (already logged in)
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`     // payout address to bind
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"` // compact base64 signature over `code`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`           // nonce from RequestLoginCode
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPayoutAddressRequest) Reset() {
	*x = SetPayoutAddressRequest{}
	mi := &file_pokerreferee_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPayoutAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPayoutAddressRequest) ProtoMessage() {}

func (x *SetPayoutAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPayoutAddressRequest.ProtoReflect.Descriptor instead.
func (*SetPayoutAddressRequest) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{25}
}

func (x *SetPayoutAddressRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SetPayoutAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SetPayoutAddressRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SetPayoutAddressRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type SetPayoutAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPayoutAddressResponse) Reset() {
	*x = SetPayoutAddressResponse{}
	mi := &file_pokerreferee_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPayoutAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPayoutAddressResponse) ProtoMessage() {}

func (x *SetPayoutAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pokerreferee_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPayoutAddressResponse.ProtoReflect.Descriptor instead.
func (*SetPayoutAddressResponse) Descriptor() ([]byte, []int) {
	return file_pokerreferee_proto_rawDescGZIP(), []int{26}
}

func (x *SetPayoutAddressResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SetPayoutAddressResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SetPayoutAddressResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_pokerreferee_proto protoreflect.FileDescriptor

const file_pokerreferee_proto_rawDesc = "" +
	"\n" +
	"\x12pokerreferee.proto\x12\x05poker\"\xc6\x01\n" +
	"\x11OpenEscrowRequest\x12!\n" +
	"\famount_atoms\x18\x01 \x01(\x04R\vamountAtoms\x12\x1d\n" +
	"\n" +
	"csv_blocks\x18\x02 \x01(\rR\tcsvBlocks\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x1f\n" +
	"\vcomp_pubkey\x18\x04 \x01(\fR\n" +
	"compPubkey\x12\x19\n" +
	"\btable_id\x18\x05 \x01(\tR\atableId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\"\xe5\x02\n" +
	"\x12OpenEscrowResponse\x12\x1b\n" +
	"\tescrow_id\x18\x01 \x01(\tR\bescrowId\x12!\n" +
	"\fdeposit_addr\x18\x02 \x01(\tR\vdepositAddr\x12*\n" +
	"\x11redeem_script_hex\x18\x03 \x01(\tR\x0fredeemScriptHex\x12\"\n" +
	"\rpk_script_hex\x18\x04 \x01(\tR\vpkScriptHex\x12\x19\n" +
	"\bmatch_id\x18\x05 \x01(\tR\amatchId\x125\n" +
	"\x16required_confirmations\x18\x06 \x01(\rR\x15requiredConfirmations\x12!\n" +
	"\froster_ready\x18\a \x01(\bR\vrosterReady\x12%\n" +
	"\x0emember_pubkeys\x18\b \x03(\fR\rmemberPubkeys\x12#\n" +
	"\rseats_pending\x18\t \x01(\rR\fseatsPending\"\x84\x02\n" +
	"\x11BindEscrowRequest\x12\x1a\n" +
	"\boutpoint\x18\x01 \x01(\tR\boutpoint\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\tR\atableId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"seat_index\x18\x04 \x01(\rR\tseatIndex\x12\x19\n" +
	"\bmatch_id\x18\x05 \x01(\tR\amatchId\x12\x14\n" +
	"\x05token\x18\x06 \x01(\tR\x05token\x12*\n" +
	"\x11redeem_script_hex\x18\a \x01(\tR\x0fredeemScriptHex\x12\x1d\n" +
	"\n" +
	"csv_blocks\x18\b \x01(\rR\tcsvBlocks\"\xbb\x02\n" +
	"\x12BindEscrowResponse\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x19\n" +
	"\btable_id\x18\x02 \x01(\tR\atableId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"seat_index\x18\x04 \x01(\rR\tseatIndex\x12\x1b\n" +
	"\tescrow_id\x18\x05 \x01(\tR\bescrowId\x12!\n" +
	"\fescrow_ready\x18\x06 \x01(\bR\vescrowReady\x12!\n" +
	"\famount_atoms\x18\a \x01(\x04R\vamountAtoms\x122\n" +
	"\x15required_amount_atoms\x18\b \x01(\x04R\x13requiredAmountAtoms\x12\x1a\n" +
	"\boutpoint\x18\t \x01(\tR\boutpoint\"K\n" +
	"\x16GetEscrowStatusRequest\x12\x1b\n" +
	"\tescrow_id\x18\x01 \x01(\tR\bescrowId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\xad\x03\n" +
	"\x17GetEscrowStatusResponse\x12\x1b\n" +
	"\tescrow_id\x18\x01 \x01(\tR\bescrowId\x12\x14\n" +
	"\x05confs\x18\x02 \x01(\rR\x05confs\x12\x1d\n" +
	"\n" +
	"utxo_count\x18\x03 \x01(\rR\tutxoCount\x12\x0e\n" +
	"\x02ok\x18\x04 \x01(\bR\x02ok\x12&\n" +
	"\x0fupdated_at_unix\x18\x05 \x01(\x03R\rupdatedAtUnix\x12!\n" +
	"\ffunding_txid\x18\x06 \x01(\tR\vfundingTxid\x12!\n" +
	"\ffunding_vout\x18\a \x01(\rR\vfundingVout\x12!\n" +
	"\famount_atoms\x18\b \x01(\x04R\vamountAtoms\x12\x1d\n" +
	"\n" +
	"csv_blocks\x18\n" +
	" \x01(\rR\tcsvBlocks\x125\n" +
	"\x16required_confirmations\x18\v \x01(\rR\x15requiredConfirmations\x12$\n" +
	"\x0emature_for_csv\x18\f \x01(\bR\fmatureForCsv\x12#\n" +
	"\rfunding_state\x18\r \x01(\tR\ffundingState\"X\n" +
	"\x18PublishSessionKeyRequest\x12\x1b\n" +
	"\tescrow_id\x18\x01 \x01(\tR\bescrowId\x12\x1f\n" +
	"\vcomp_pubkey\x18\x02 \x01(\fR\n" +
	"compPubkey\"A\n" +
	"\x19PublishSessionKeyResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xb4\x02\n" +
	"\x17SettlementStreamMessage\x12.\n" +
	"\x05hello\x18\x01 \x01(\v2\x16.poker.SettlementHelloH\x00R\x05hello\x128\n" +
	"\rneed_pre_sigs\x18\x02 \x01(\v2\x12.poker.NeedPreSigsH\x00R\vneedPreSigs\x12A\n" +
	"\x10provide_pre_sigs\x18\x03 \x01(\v2\x15.poker.ProvidePreSigsH\x00R\x0eprovidePreSigs\x125\n" +
	"\tverify_ok\x18\x04 \x01(\v2\x16.poker.VerifyPreSigsOkH\x00R\bverifyOk\x12.\n" +
	"\x05error\x18\x05 \x01(\v2\x16.poker.SettlementErrorH\x00R\x05errorB\x05\n" +
	"\x03msg\"\xba\x01\n" +
	"\x0fSettlementHello\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1b\n" +
	"\tescrow_id\x18\x02 \x01(\tR\bescrowId\x12\x1f\n" +
	"\vcomp_pubkey\x18\x03 \x01(\fR\n" +
	"compPubkey\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x19\n" +
	"\btable_id\x18\x05 \x01(\tR\atableId\x12\x1d\n" +
	"\n" +
	"seat_index\x18\x06 \x01(\rR\tseatIndex\"\xb9\x01\n" +
	"\vNeedPreSigs\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\x05R\x06branch\x12 \n" +
	"\fdraft_tx_hex\x18\x03 \x01(\tR\n" +
	"draftTxHex\x12/\n" +
	"\x06inputs\x18\x04 \x03(\v2\x17.poker.NeedPreSigsInputR\x06inputs\x12$\n" +
	"\x04kind\x18\x05 \x01(\x0e2\x10.poker.DraftKindR\x04kind\"\x8d\x02\n" +
	"\x10NeedPreSigsInput\x12\x19\n" +
	"\binput_id\x18\x01 \x01(\tR\ainputId\x12*\n" +
	"\x11redeem_script_hex\x18\x02 \x01(\tR\x0fredeemScriptHex\x12\x1f\n" +
	"\vsighash_hex\x18\x03 \x01(\tR\n" +
	"sighashHex\x12*\n" +
	"\x11adaptor_point_hex\x18\x04 \x01(\tR\x0fadaptorPointHex\x12\x1f\n" +
	"\vinput_index\x18\x05 \x01(\rR\n" +
	"inputIndex\x12!\n" +
	"\famount_atoms\x18\x06 \x01(\x04R\vamountAtoms\x12!\n" +
	"\fowner_pubkey\x18\a \x01(\fR\vownerPubkey\"\xc4\x01\n" +
	"\x0eProvidePreSigs\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\x05R\x06branch\x12-\n" +
	"\apresigs\x18\x03 \x03(\v2\x13.poker.PreSignatureR\apresigs\x12*\n" +
	"\x06cosigs\x18\x04 \x03(\v2\x12.poker.CoSignatureR\x06cosigs\x12$\n" +
	"\x04kind\x18\x05 \x01(\x0e2\x10.poker.DraftKindR\x04kind\"x\n" +
	"\fPreSignature\x12\x19\n" +
	"\binput_id\x18\x01 \x01(\tR\ainputId\x12-\n" +
	"\x13r_prime_compact_hex\x18\x02 \x01(\tR\x10rPrimeCompactHex\x12\x1e\n" +
	"\vs_prime_hex\x18\x03 \x01(\tR\tsPrimeHex\"f\n" +
	"\vCoSignature\x12\x19\n" +
	"\binput_id\x18\x01 \x01(\tR\ainputId\x12#\n" +
	"\rsigner_pubkey\x18\x02 \x01(\fR\fsignerPubkey\x12\x17\n" +
	"\asig_hex\x18\x03 \x01(\tR\x06sigHex\"j\n" +
	"\x0fVerifyPreSigsOk\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\x05R\x06branch\x12$\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x10.poker.DraftKindR\x04kind\"B\n" +
	"\x0fSettlementError\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"V\n" +
	"\x18GetFinalizeBundleRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1f\n" +
	"\vwinner_seat\x18\x02 \x01(\x05R\n" +
	"winnerSeat\"\xbb\x01\n" +
	"\x19GetFinalizeBundleResponse\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\x05R\x06branch\x12 \n" +
	"\fdraft_tx_hex\x18\x03 \x01(\tR\n" +
	"draftTxHex\x12\x1b\n" +
	"\tgamma_hex\x18\x04 \x01(\tR\bgammaHex\x12,\n" +
	"\x06inputs\x18\x05 \x03(\v2\x14.poker.FinalizeInputR\x06inputs\"\x95\x02\n" +
	"\rFinalizeInput\x12\x19\n" +
	"\binput_id\x18\x01 \x01(\tR\ainputId\x12-\n" +
	"\x13r_prime_compact_hex\x18\x02 \x01(\tR\x10rPrimeCompactHex\x12\x1e\n" +
	"\vs_prime_hex\x18\x03 \x01(\tR\tsPrimeHex\x12\x1f\n" +
	"\vinput_index\x18\x04 \x01(\rR\n" +
	"inputIndex\x12*\n" +
	"\x11redeem_script_hex\x18\x05 \x01(\tR\x0fredeemScriptHex\x12*\n" +
	"\x06cosigs\x18\x06 \x03(\v2\x12.poker.CoSignatureR\x06cosigs\x12!\n" +
	"\fowner_pubkey\x18\a \x01(\fR\vownerPubkey\"k\n" +
	"\x0fPostBondRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\boutpoint\x18\x02 \x01(\tR\boutpoint\x12&\n" +
	"\x0fbond_script_hex\x18\x03 \x01(\tR\rbondScriptHex\"&\n" +
	"\x0eGetBondRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x94\x02\n" +
	"\x10PostBondResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1a\n" +
	"\boutpoint\x18\x02 \x01(\tR\boutpoint\x12!\n" +
	"\famount_atoms\x18\x03 \x01(\x04R\vamountAtoms\x12\x1f\n" +
	"\vlock_blocks\x18\x04 \x01(\rR\n" +
	"lockBlocks\x12\x14\n" +
	"\x05confs\x18\x05 \x01(\rR\x05confs\x12!\n" +
	"\fowner_pubkey\x18\x06 \x01(\fR\vownerPubkey\x12%\n" +
	"\x0erequired_atoms\x18\a \x01(\x04R\rrequiredAtoms\x120\n" +
	"\x14required_lock_blocks\x18\b \x01(\rR\x12requiredLockBlocks\"D\n" +
	"\x11AbortMatchRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"F\n" +
	"\x12AbortMatchResponse\x12\x12\n" +
	"\x04txid\x18\x01 \x01(\tR\x04txid\x12\x1c\n" +
	"\tbroadcast\x18\x02 \x01(\bR\tbroadcast\"{\n" +
	"\x17SetPayoutAddressRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\"Z\n" +
	"\x18SetPayoutAddressResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress*<\n" +
	"\tDraftKind\x12\x19\n" +
	"\x15DRAFT_KIND_SETTLEMENT\x10\x00\x12\x14\n" +
	"\x10DRAFT_KIND_ABORT\x10\x012\x92\x06\n" +
	"\fPokerReferee\x12C\n" +
	"\n" +
	"OpenEscrow\x12\x18.poker.OpenEscrowRequest\x1a\x19.poker.OpenEscrowResponse\"\x00\x12C\n" +
	"\n" +
	"BindEscrow\x12\x18.poker.BindEscrowRequest\x1a\x19.poker.BindEscrowResponse\"\x00\x12X\n" +
	"\x11PublishSessionKey\x12\x1f.poker.PublishSessionKeyRequest\x1a .poker.PublishSessionKeyResponse\"\x00\x12X\n" +
	"\x10SettlementStream\x12\x1e.poker.SettlementStreamMessage\x1a\x1e.poker.SettlementStreamMessage\"\x00(\x010\x01\x12X\n" +
	"\x11GetFinalizeBundle\x12\x1f.poker.GetFinalizeBundleRequest\x1a .poker.GetFinalizeBundleResponse\"\x00\x12R\n" +
	"\x0fGetEscrowStatus\x12\x1d.poker.GetEscrowStatusRequest\x1a\x1e.poker.GetEscrowStatusResponse\"\x00\x12U\n" +
	"\x10SetPayoutAddress\x12\x1e.poker.SetPayoutAddressRequest\x1a\x1f.poker.SetPayoutAddressResponse\"\x00\x12C\n" +
	"\n" +
	"AbortMatch\x12\x18.poker.AbortMatchRequest\x1a\x19.poker.AbortMatchResponse\"\x00\x12=\n" +
	"\bPostBond\x12\x16.poker.PostBondRequest\x1a\x17.poker.PostBondResponse\"\x00\x12;\n" +
	"\aGetBond\x12\x15.poker.GetBondRequest\x1a\x17.poker.PostBondResponse\"\x00B\x0fZ\rgrpc/pokerrpcb\x06proto3"

var (
	file_pokerreferee_proto_rawDescOnce sync.Once
	file_pokerreferee_proto_rawDescData []byte
)

func file_pokerreferee_proto_rawDescGZIP() []byte {
	file_pokerreferee_proto_rawDescOnce.Do(func() {
		file_pokerreferee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pokerreferee_proto_rawDesc), len(file_pokerreferee_proto_rawDesc)))
	})
	return file_pokerreferee_proto_rawDescData
}

var file_pokerreferee_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pokerreferee_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_pokerreferee_proto_goTypes = []any{
	(DraftKind)(0),                    // 0: poker.DraftKind
	(*OpenEscrowRequest)(nil),         // 1: poker.OpenEscrowRequest
	(*OpenEscrowResponse)(nil),        // 2: poker.OpenEscrowResponse
	(*BindEscrowRequest)(nil),         // 3: poker.BindEscrowRequest
	(*BindEscrowResponse)(nil),        // 4: poker.BindEscrowResponse
	(*GetEscrowStatusRequest)(nil),    // 5: poker.GetEscrowStatusRequest
	(*GetEscrowStatusResponse)(nil),   // 6: poker.GetEscrowStatusResponse
	(*PublishSessionKeyRequest)(nil),  // 7: poker.PublishSessionKeyRequest
	(*PublishSessionKeyResponse)(nil), // 8: poker.PublishSessionKeyResponse
	(*SettlementStreamMessage)(nil),   // 9: poker.SettlementStreamMessage
	(*SettlementHello)(nil),           // 10: poker.SettlementHello
	(*NeedPreSigs)(nil),               // 11: poker.NeedPreSigs
	(*NeedPreSigsInput)(nil),          // 12: poker.NeedPreSigsInput
	(*ProvidePreSigs)(nil),            // 13: poker.ProvidePreSigs
	(*PreSignature)(nil),              // 14: poker.PreSignature
	(*CoSignature)(nil),               // 15: poker.CoSignature
	(*VerifyPreSigsOk)(nil),           // 16: poker.VerifyPreSigsOk
	(*SettlementError)(nil),           // 17: poker.SettlementError
	(*GetFinalizeBundleRequest)(nil),  // 18: poker.GetFinalizeBundleRequest
	(*GetFinalizeBundleResponse)(nil), // 19: poker.GetFinalizeBundleResponse
	(*FinalizeInput)(nil),             // 20: poker.FinalizeInput
	(*PostBondRequest)(nil),           // 21: poker.PostBondRequest
	(*GetBondRequest)(nil),            // 22: poker.GetBondRequest
	(*PostBondResponse)(nil),          // 23: poker.PostBondResponse
	(*AbortMatchRequest)(nil),         // 24: poker.AbortMatchRequest
	(*AbortMatchResponse)(nil),        // 25: poker.AbortMatchResponse
	(*SetPayoutAddressRequest)(nil),   // 26: poker.SetPayoutAddressRequest
	(*SetPayoutAddressResponse)(nil),  // 27: poker.SetPayoutAddressResponse
}
var file_pokerreferee_proto_depIdxs = []int32{
	10, // 0: poker.SettlementStreamMessage.hello:type_name -> poker.SettlementHello
	11, // 1: poker.SettlementStreamMessage.need_pre_sigs:type_name -> poker.NeedPreSigs
	13, // 2: poker.SettlementStreamMessage.provide_pre_sigs:type_name -> poker.ProvidePreSigs
	16, // 3: poker.SettlementStreamMessage.verify_ok:type_name -> poker.VerifyPreSigsOk
	17, // 4: poker.SettlementStreamMessage.error:type_name -> poker.SettlementError
	12, // 5: poker.NeedPreSigs.inputs:type_name -> poker.NeedPreSigsInput
	0,  // 6: poker.NeedPreSigs.kind:type_name -> poker.DraftKind
	14, // 7: poker.ProvidePreSigs.presigs:type_name -> poker.PreSignature
	15, // 8: poker.ProvidePreSigs.cosigs:type_name -> poker.CoSignature
	0,  // 9: poker.ProvidePreSigs.kind:type_name -> poker.DraftKind
	0,  // 10: poker.VerifyPreSigsOk.kind:type_name -> poker.DraftKind
	20, // 11: poker.GetFinalizeBundleResponse.inputs:type_name -> poker.FinalizeInput
	15, // 12: poker.FinalizeInput.cosigs:type_name -> poker.CoSignature
	1,  // 13: poker.PokerReferee.OpenEscrow:input_type -> poker.OpenEscrowRequest
	3,  // 14: poker.PokerReferee.BindEscrow:input_type -> poker.BindEscrowRequest
	7,  // 15: poker.PokerReferee.PublishSessionKey:input_type -> poker.PublishSessionKeyRequest
	9,  // 16: poker.PokerReferee.SettlementStream:input_type -> poker.SettlementStreamMessage
	18, // 17: poker.PokerReferee.GetFinalizeBundle:input_type -> poker.GetFinalizeBundleRequest
	5,  // 18: poker.PokerReferee.GetEscrowStatus:input_type -> poker.GetEscrowStatusRequest
	26, // 19: poker.PokerReferee.SetPayoutAddress:input_type -> poker.SetPayoutAddressRequest
	24, // 20: poker.PokerReferee.AbortMatch:input_type -> poker.AbortMatchRequest
	21, // 21: poker.PokerReferee.PostBond:input_type -> poker.PostBondRequest
	22, // 22: poker.PokerReferee.GetBond:input_type -> poker.GetBondRequest
	2,  // 23: poker.PokerReferee.OpenEscrow:output_type -> poker.OpenEscrowResponse
	4,  // 24: poker.PokerReferee.BindEscrow:output_type -> poker.BindEscrowResponse
	8,  // 25: poker.PokerReferee.PublishSessionKey:output_type -> poker.PublishSessionKeyResponse
	9,  // 26: poker.PokerReferee.SettlementStream:output_type -> poker.SettlementStreamMessage
	19, // 27: poker.PokerReferee.GetFinalizeBundle:output_type -> poker.GetFinalizeBundleResponse
	6,  // 28: poker.PokerReferee.GetEscrowStatus:output_type -> poker.GetEscrowStatusResponse
	27, // 29: poker.PokerReferee.SetPayoutAddress:output_type -> poker.SetPayoutAddressResponse
	25, // 30: poker.PokerReferee.AbortMatch:output_type -> poker.AbortMatchResponse
	23, // 31: poker.PokerReferee.PostBond:output_type -> poker.PostBondResponse
	23, // 32: poker.PokerReferee.GetBond:output_type -> poker.PostBondResponse
	23, // [23:33] is the sub-list for method output_type
	13, // [13:23] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_pokerreferee_proto_init() }
func file_pokerreferee_proto_init() {
	if File_pokerreferee_proto != nil {
		return
	}
	file_pokerreferee_proto_msgTypes[8].OneofWrappers = []any{
		(*SettlementStreamMessage_Hello)(nil),
		(*SettlementStreamMessage_NeedPreSigs)(nil),
		(*SettlementStreamMessage_ProvidePreSigs)(nil),
		(*SettlementStreamMessage_VerifyOk)(nil),
		(*SettlementStreamMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pokerreferee_proto_rawDesc), len(file_pokerreferee_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pokerreferee_proto_goTypes,
		DependencyIndexes: file_pokerreferee_proto_depIdxs,
		EnumInfos:         file_pokerreferee_proto_enumTypes,
		MessageInfos:      file_pokerreferee_proto_msgTypes,
	}.Build()
	File_pokerreferee_proto = out.File
	file_pokerreferee_proto_goTypes = nil
	file_pokerreferee_proto_depIdxs = nil
}
